"""initial

Revision ID: 2838d0a6db39
Revises: 
Create Date: 2026-08-28 11:33:48.317611

"""

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# Идентификаторы ревизий используемые Alembic.
revision = '2838d0a6db39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'published', 'failed', name='outbox_status'), server_default='pending', nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('backoff_delay', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_dispatch', 'outbox', ['status', 'created_at'], unique=False)
    op.create_table('payments',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('RUB', 'USD', 'EUR', name='payment_currency'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', name='payment_status'), server_default='pending', nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('webhook_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('payment_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_payments_status_created_at', 'payments', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_status_created_at', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_outbox_dispatch', table_name='outbox')
    op.drop_table('outbox')
    # ### end Alembic commands ###
